### ISSUE TITLE
Mixlib::Install::Options::InvalidOptions: Unknown architecture the. on Windows Server 2016 

### ISSUE THREAD

**Issue by rayterrill** [chef/mixlib-install#277]
# Version:

3.11

# Environment:

* Used as part of chef_client_updater cookbook
* Running on Windows Server 2016

# Scenario:

Fails to update chef_client because mixlib::Install returns an invalid architecture:
```
    Mixlib::Install::Options::InvalidOptions
    ----------------------------------------
    Unknown architecture the.
    Must be one of: aarch64, i386, powerpc, ppc64, ppc64le, s390x, sparc, x86_64
```

# Steps to Reproduce:

Unknown.

# Expected Result:

Should return x86_64 as the architecture.

# Actual Result:

```
    ================================================================================
    Error executing action `update` on resource 'chef_client_updater[Install latest Chef]'
    ================================================================================

    Mixlib::Install::Options::InvalidOptions
    ----------------------------------------
    Unknown architecture the.
    Must be one of: aarch64, i386, powerpc, ppc64, ppc64le, s390x, sparc, x86_64

    Cookbook Trace:
    ---------------
    c:/chef/cache/cookbooks/chef_client_updater/providers/default.rb:125:in `new'
    c:/chef/cache/cookbooks/chef_client_updater/providers/default.rb:125:in `mixlib_install'
    c:/chef/cache/cookbooks/chef_client_updater/providers/default.rb:156:in `desired_version'
    c:/chef/cache/cookbooks/chef_client_updater/providers/default.rb:168:in `update_necessary?'
    c:/chef/cache/cookbooks/chef_client_updater/providers/default.rb:462:in `block in class_from_file'

    Resource Declaration:
    ---------------------
    # In c:/chef/cache/cookbooks/POP_Base/recipes/default.rb

     10: chef_client_updater 'Install latest Chef' do
     11:   version '14'
     12: end
     13:

    Compiled Resource:
    ------------------
    # Declared in c:/chef/cache/cookbooks/POP_Base/recipes/default.rb:10:in `from_file'

    chef_client_updater("Install latest Chef") do
      action [:update]
      default_guard_interpreter :default
      declared_type :chef_client_updater
      cookbook_name "POP_Base"
      recipe_name "default"
      version "14"
    end

    System Info:
    ------------
    chef_version=13.8.5
    platform=windows
    platform_version=10.0.14393
    ruby=ruby 2.4.3p205 (2017-12-14 revision 61247) [x64-mingw32]
    program_name=C:/opscode/chef/bin/chef-client
    executable=C:/opscode/chef/bin/chef-client
```

**Comment by tas50** [comment]
I assume this happens on a x86_64 box? Any chance you can get me the ohai output. If you don't wan to post it here you can e-mail it to me at tsmith@chef.io

**Comment by rayterrill** [comment]
@tas50 Email sent. Let me know if I can provide any more info.

**Comment by rayterrill** [comment]
@tas50 were you able to look into this mate? Any workaround potentially?

**Comment by gaelik** [comment]
We have the same issue here, let us know if you need more debug/output logs

**Comment by tas50** [comment]
@gaelik is your issue also coming from the updater cookbook or is it from the install.ps1 script directly?

**Comment by derrike** [comment]
I have the same issue - using Windows Server 2016 & Windows Server 2019 w/ the updater cookbook.
